/* Generated by Together */

package ProblemDomain;

/**
 * An Event is used to mark real-world occurrences of importance that will happen at a specific time, such as an employee meeting or a business provided lunch event.  Events may be sent to all employees within a workgroup, or a within a job type. 
 */
public class Event {
    /**
     * Used to save a newly created event, which should include either a target job type or target workgroup, the start and end dates/times, and description of the event. 
     */
    public void newEvent(Event event){}

    /**
     * Removes an event from the system. 
     */
    public void removeEvent() {
    }

    /**
     * The job type for which all employees will see the event. 
     */
    private JobType empType;

    /**
     * The workgroup for which all employees will see the event. 
     */
    private Workgroup workgroup;

    /**
     * The date and time at which the event is scheduled to begin. 
     */
    private Date startDate;

    /**
     * The time at which the event is scheduled to end. 
     */
    private Date endDate;

    /**
     * A short description of what the event is. 
     */
    private String description;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 0..1
     * @clientQualifier may have
     * @supplierQualifier applies to 
     */
    private JobType lnkJobType;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 0..1
     * @clientQualifier may have
     * @supplierQualifier applies to 
     */
    private Workgroup lnkWorkgroup;
}
