/* Generated by Together */

package ProblemDomain;

/**
 * A shift contains information on the specific time and place that one or more employees will be working. 
 */
public class Shift {
    /**
     * The time at which work begins for the employees assigned to the shift. 
     */
    private Time startTime;

    /**
     * The time at which work ends for the employees assigned to the shift. 
     */
    private Time endTime;
    private ShiftPos[] positions;

    /**
     * @clientQualifier contains
     * @supplierCardinality 1..*
     * @supplierQualifier required by
     * @clientCardinality 1 
     */
    private ShiftPos lnkShiftPos;
}
