/* Generated by Together */

package ProblemDomain;

public class ShiftTemplate {
    private Shift[] shifts;

    /**
     * @clientQualifier contains
     * @supplierCardinality 1..*
     * @supplierQualifier defines
     * @clientCardinality 1 
     */
    private Shift lnkShift;
}
