/* Generated by Together */

package ProblemDomain;

/**
 * Holds global settings that will apply to all employees in the system. 
 */
public class SystemSettings {
    /**
     * The time in days before a shift starts that shift requests for it will be cancelled and the requestee notified. 
     */
    private int shiftRequestCutoff;

    /**
     * The minimum shift length that employees will be paid for, in the format HH:MM.  With a limit of 03:00, an employee who is works for two hours will still be recorded as being paid for three.  00:00 by default. 
     */
    private String minShiftDuration;

    /**
     * Minimum amount of days that must pass between changes in availability by an employee. 
     */
    private int availabilityChangeHold;

    /**
     * Maximum amount of consecutive days that can be taken off on emergency leave.  Days beyond this amount will require additional discussion between the employee and their supervisor. 
     */
    private int maxEmergencyDuration;
}
