/* Generated by Together */

package ProblemDomain;

/**
 * An Event is used to mark real-world occurrences of importance that will happen at a specific time, such as an employee meeting or a business provided lunch event.  Events may be sent to all employees within a workgroup, or a within a job type. 
 */
public class WorkingShift {
    private Time startTime;
    private Time endTime;
    private Employee[] employees;

    /**
     * @supplierQualifier contains
     * @clientCardinality 1..*
     * @clientQualifier is contained by
     * @supplierCardinality 1 
     */
    private Schedule lnkSchedule;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 1..*
     * @clientQualifier contains
     * @supplierQualifier works 
     */
    private Employee lnkEmployee;
}
