/* Generated by Together */

package Persistence;

import Business.GlobalSettings;

/**
 * Provides functionality for retrieving, creating, updating and deleting GlobalSettings data from the database. 
 */
public class GlobalSettingsBroker implements Broker {
}
