/* Generated by Together */

package Persistence;


/**
 * Provides functionality for retrieving, creating, updating and deleting GlobalSettings data from the database. 
 */
public class GlobalSettingsBroker implements Broker {
}
