/* Generated by Together */

package Persistence;

/**
 * Provides functionality for retrieving, creating, updating and deleting Location data from the database. 
 */
public class LocationBroker implements Broker {
}
