/* Generated by Together */

package Persistence;

/**
 * Provides functionality to add, update and delete notifications in the database.
 */
public class NotificationBroker implements Broker {
    /**
     * Must be used to get a Broker, ensures that singleton pattern is enforced. 
     */
    public NotificationBroker getBroker() {
    }

    /**
     * Static representation of the broker. Initialized the first time getBroker is called. 
     */
    private NotificationBroker nbrok;
}
