/* Generated by Together */

package Persistence;

/**
 * Provides functionality for retrieving, creating, updating and deleting Notification data from the database.
 */
public class NotificationBroker implements Broker {
}
