/* Generated by Together */

package Persistence;

/**
 * Provides functionality for retrieving, creating, updating and deleting PermissionSet data from the database.
 */
public class PermissionSetBroker implements Broker {
}
