/* Generated by Together */

package Persistence;

/**
 * Provides functionality for retrieving, creating, updating and deleting PermissionSet data from the database.
 */
public class PermissionBroker implements Broker {
    /**
     * Must be used to get a Broker, ensures that singleton pattern is enforced. 
     */
    public PermissionBroker getBroker() {
    }

    /**
     * Returns all the permission levels that are below a certain Employee's built in permission level. This way, an employee does not have to worry about level inputs and it applies to the caller automatically, or if a higher-permissioned employee calls this using an employee under them, it will return that data. A higher-level employee should not be returned to an under-privileged user at any point, unless it's basic name/contact data for supervisors of an Employee. 
     */
    public PermissionLevel getAllBelow() {
    }

    /**
     * Static representation of the broker. Initialized the first time getBroker is called. 
     */
    private PermissionBroker pbrok;
}
