/* Generated by Together */

package Persistence;

import Business.Position;

/**
 * Provides functionality for retrieving, creating, updating and deleting Position data from the database. 
 */
public class PositionBroker implements Broker {
}
