/* Generated by Together */

package Persistence;

/**
 * Provides functionality for adding, updating and deleting Rules in the database. 
 */
public class RuleBroker implements Broker {
    /**
     * Must be used to get a Broker, ensures that singleton pattern is enforced. 
     */
    public RuleBroker getBroker() {
    }

    /**
     * Static representation of the broker. Initialized the first time getBroker is called. 
     */
    private RuleBroker rbrok;
}
