/* Generated by Together */

package Persistence;

import Business.Schedule;

/**
 * Provides functionality for retrieving, creating, updating and deleting Schedule data from the database.
 */
public class ScheduleBroker implements Broker {
}
