/* Generated by Together */

package Persistence;

/**
 * Provides functionality for retrieving, creating, updating and deleting ScheduleTemplate data from the database. 
 */
public class ScheduleTemplateBroker implements Broker {
}
