/* Generated by Together */

package Persistence;

import Business.Skill;

/**
 * Provides functionality for retrieving, creating, updating and deleting Position data from the database. 
 */
public class SkillBroker implements Broker {
}
