/* Generated by Together */

package Interface;

public class Dashboard {
    public void dispSchedView(){}

    public void dispReportView(){}

    public void dispEventView(){}

    public void dispDashboard() {
    }
}
