/* Generated by Together */

package Interface;

public class LogInWidget extends Widget {
    public void getLogInUsername() {
    }

    public void getLogInPassword() {
    }

    public void logInButtonAction() {
    }

    public Boolean checkEmps() {
    }
}
