/* Generated by Together */

package Interface;

public class Request_Widget extends Widget {
    public Requests[] loadEmpRequests() {
    }

    public Boolean acceptRequest() {
    }

    public Boolean deleteRequest() {
    }

    public Boolean updateRequest() {
    }
}
