/* Generated by Together */

package Interface;

public class ScheduleWidget extends Widget {
    public void loadShifts(){}

    public void dispWeeklySched(){}

    public void disableWorkgroupList(){}

    public void dispDailySched(){}

    public void displayNotification() {
    }
}
