/* Generated by Together */

package Interface;

/**
 * Provides the user interface that will be used to change employee specific permission settings. 
 */
public class SettingsWidget extends Widget {
    /**
     * Adds an employee as a supervisor within the system, and sets their permissions accordingly. 
     */
    public void addSupervisor() {
    }

    /**
     * Creates a new employee type, which can then be applied to any employees within the system. 
     */
    public void createEmpType() {
    }

    /**
     * Increases an employees permission level. 
     */
    public void promote() {
    }

    /**
     * Inserts a new employee type, based off of data from outside the system. 
     */
    public void insertEmpType() {
    }
}
