/* Generated by Together */

package Interface;

public class WebUI {
    public void loadSchedView(){}

    public void showDayWeekDialog(){}

    public void loadShifts(){}

    public void displaySched(){}

    public void dispSched(){}
}
