/* Generated by Together */

package Interface;

/**
 * Provides the user interface for creating and managing workgroups that exist within the system. 
 */
public class WorkgroupWidget extends Widget {
    /**
     * Shows a list of all available workgroups that can be edited or deleted by the supervisor. 
     */
    public void showWkgpList(){}

    /**
     * Shows the edit workgroup view, used to add or remove employees from a workgroup. 
     */
    public void showEditView(){}

    /**
     * Fetches a new workgroup through the broker, and makes it available in the edit view for available employees to be added to it. 
     */
    public void getNewWkgp(){}

    /**
     * Gets confirmation from the user before applying a specific change, such as deleting a workgroup, or saving changes after a workgroup has been edited. 
     */
    public void getChangeConf(){}

    /**
     * Saves all changes to the currently viewed workgroup to the database. 
     */
    public void saveChanges(){}

    /**
     * Loads a selected workgroup so that it can be edited. 
     */
    public void loadWkgp(){}
}
