/* Generated by Together */

package Interface;

/**
 * Provides the user interface for creating and managing events that exist within the system. 
 */
public class EventWidget extends Widget {
    /**
     * Displays a list of available event types, allowing the user to choose what type of event they wish to create. 
     */
    public void dispTypeView(){}

    /**
     * Creates a new event that will be sent to all employees within a specific workgroup. 
     */
    public void workgroupEvent(){}

    /**
     * Loads a list of all available workgroups that the supervisor has access to, allowing them to choose what workgroup they want the event to be sent to. 
     */
    public void loadWorkgroupList(){}

    /**
     * Creates a new event that will be sent to all employees within a specific job type. 
     */
    public void jobTypeEvent(){}

    /**
     * Loads a list of all available job types that the supervisor has access to, allowing them to choose what job type they want the event to be sent to. 
     */
    public void loadJobTypeList(){}
}
