/* Generated by Together */

package Interface;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
public class GenerateSchedule extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void service(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        response.setContentType("text/html");
        PrintWriter out = new PrintWriter(response.getOutputStream());
        //
        //Write your code here
        //
        out.println("<HTML>");
        out.println("<HEAD><TITLE>GenerateSchedule Output</TITLE>");
        out.println("</HEAD>");
        out.println("<BODY>");
        //
        //Write your HTML here
        //
        out.println("</BODY>");
        out.println("</HTML>");
        out.flush();
    }
}
