/* Generated by Together */

package Interface;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Used to log a user out of the system and to invalidate the session. 
 */
public class Logout extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
