/* Generated by Together */

package Interface;

/**
 * Provides functionality for adding, editing and deleting positions. 
 */
public class PositionsWidget extends Widget {
    /**
     * Populates the existing positions list with positions from the database. 
     */
    public void loadPositions(){}

    /**
     * Shows the edit position view with all fields blank for the user to create a new position. 
     */
    public void showEditView(){}

    /**
     * Shows the edit position view with all fields filled with data from the chosen position. 
     */
    public void showEditView(Position p0){}

    /**
     * Display an alert, showing the user that the position was saved or created. 
     */
    public void showPositionSaved(){}

    /**
     * Prompts the user to confirm that they wish to delete the position. 
     */
    public void confirmDelete(){}

    /**
     * Display an alert, showing the user that the chosen position was deleted. 
     */
    public void showPositionDeleted(){}

    /** @link dependency */
    /*# SkillsWidget lnkSkillsWidget; */
}
