/* Generated by Together */

package Interface;

/**
 * Provides functionality for adding, editing and deleting positions. 
 */
public class PositionsWidget extends Widget {
    /** @link dependency */
    /*# SkillsWidget lnkSkillsWidget; */
}
