/* Generated by Together */

package Interface;

/**
 * Provides the user interface that employees will use to send requests to their supervisor, and will also be used by supervisors to manage any requests they have received. 
 */
public class Request_Widget extends Widget {
    /**
     * Gets the list of all current requests that have been sent by employees. 
     */
    public Requests[] loadEmpRequests() {
    }

    /**
     * Accepts a selected request, notifying the employee of the decision. 
     */
    public Boolean acceptRequest() {
    }

    /**
     * Deletes a selected request.  This is equivalent to rejecting a request, and the employee that sent it will be notified accordingly. 
     */
    public Boolean deleteRequest() {
    }

    /**
     * Updates a request, allowing notifications to be sent to the requestee that 
     */
    public Boolean updateRequest() {
    }
}
