/* Generated by Together */

package Interface;

/**
 * Provides the user interface for creating and managing schedules that exist within the system. 
 */
public class ScheduleWidget extends Widget {
    /**
     * Loads all shifts that are contained within a given schedule. 
     */
    public void loadShifts(){}

    /**
     * Displays the schedule in a weekly format. 
     */
    public void dispWeeklySched(){}

    /**
     * Displays the schedule in a daily format. 
     */
    public void dispDailySched(){}
}
