/* Generated by Together */

package Interface;

/**
 * A widget that can be used in the dashboard as a tab, that when clicked, will switch the currently displayed widget to the selected one. 
 */
public class TabWidget extends Widget {
}
