/* Generated by Together */

package Interface.skill;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Will update a skill in the system using the skill management screen. 
 */
public class UpdateSkill extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
