-- These are extra lines that are needed for our create script to work properly,
-- but aren't made when the script is generated by MySQL Workbench.

DROP USER 'WABroker'@'localhost';
CREATE USER 'WABroker'@'localhost' IDENTIFIED BY 'password';

grant SELECT, INSERT, UPDATE, DELETE on TABLE `WebAgenda`.* to 'WABroker'@'localhost';
grant SELECT, LOCK TABLES on *.* to 'WABroker'@'localhost';

FLUSH PRIVILEGES;
