-- These are extra lines that are needed for our create script to work properly,
-- but aren't made when the script is generated by MySQL Workbench.

DROP USER 'WABroker'@'localhost';
FLUSH PRIVILEGES;
