/* Generated by Together */

package Application;

/**
 * Provides basic functionality for running hot backups on the system. 
 */
public class Backup {
    /**
     * Creates a new backup of the WebAgenda database and all information it contains, using the given installation directory for the existing MySQL server, and the target save directory.
     * 
     * Returns a string containing the absolute path to the newly created sql file. 
     */
    public String backupDB() {
    }
}
