/* Generated by Together */

package Application;

/**
 * Wrapper for JDBC database connections, used to provide additional functionality for connection pooling. 
 */
public class DBConnection {
    /**
     * Returns the database connection object so that statements can be sent through it. Each getConnection() request from this class will reset the access time to current date. 
     */
    public Connection getConnection() {
    }

    /**
     * Returns the time that the connection was last accessed. 
     */
    public long getAccessTime() {
    }

    /**
     * Database connection object that statements and queries are sent through. 
     */
    private Connection conn;

    /**
     * Determines when connection was last accessed so unused connections can be closed and their memory returned. 
     */
    private long lastAccess;

    /**
     * True if this connection object is in use and cannot be closed. Connections are only closed when isAvailable is true and hasn't been accessed for a specific duration. 
     */
    private boolean isAvailable;
}
