/* Generated by Together */

package Application;

/**
 * Provides functionality for all actions used by the Generate Report and Distribute Report use cases. 
 */
public class GenerateReport {
    /**
     * Generates a new schedule report. 
     */
    public void genSchRep(){}

    /**
     * Calculates scheduling statistics, used when generating a schedule report. 
     */
    public void getSchStats(){}

    /**
     * Generates a new employee resource report. 
     */
    public void genResRep(){}

    /**
     * Calculates employee resource statistics, used when generating an employee resource report. 
     */
    public void getResStats(){}

    /**
     * Generates a employee system usage report. 
     */
    public void genUseRep(){}

    /**
     * Generates employee usage statistics, used when generating an employee usage report. 
     */
    public void getUseStats(){}

    /**
     * Converts a generated report into a print-friendly format. 
     */
    public void convertPrintRep(){}
}
