/* Generated by Together */

package Application;

public class GenerateReport {
    public void genSchRep(){}

    public void getSchStats(){}

    public void genResRep(){}

    public void getResStats(){}

    public void genUseRep(){}

    public void getUseStats(){}
}
