/* Generated by Together */

package Application;

/**
 * Provides functionality for all actions used by the Maintain Location use case. 
 */
public class MaintainLocation {
    /**
     * Confirms that the location has no errors that would prevent it from being written to the database.  Will also check if the location already exists in the database. 
     */
    public boolean validate(Location p0){}
}
