/* Generated by Together */

package Application;

/**
 * Provides functionality for all actions used by the Maintain Skill use case. 
 */
public class MaintainSkill {
    /**
     * Confirms that the skill has no errors that would prevent it from being written to the database.  Will also check if the skill already exists in the database. 
     */
    public boolean validate(Skill p0){}
}
