/* Generated by Together */

package Application;

import Business.Schedule;
public class MaintainEmployee {
    public void setAvailability(Schedule p0){}

    /**
     * Send a schedule into pending state for a change in availability. 
     */
    public void pendingAvailability(Schedule p0){}
}
