/* Generated by Together */

package Application;

/**
 * Provides functionality for all actions used by the Maintain Position use case. 
 */
public class MaintainPosition {
    /**
     * Confirms that the position has no errors that would prevent it from being written to the database.  Will also check if the position already exists in the database. 
     */
    public boolean validate(Position p0){}
}
