/* Generated by Together */

package Application;

import Business.Schedule;

/**
 * Provides functionality for all actions used by the Maintain Schedule use case. 
 */
public class MaintainSchedule {
    /**
     * Returns a schedule that is saved but not active. Returns null if no future schedule exists.
     */
    public void getFutureSchedule(int p0){}

    /**
     * Takes an array of schedules and adds the shifts of all into one, which is returned. 
     */
    public Schedule mergeSchedule(Schedule[] p0){}

    /**
     * Sets the schedule for a certain day (the string param is a date) with the shift[] 's specified. 
     */
    protected void createSchedule(String p0, Shift[] p1){}

    /**
     * Clears a schedule by removing all shifts.
     */
    public void clearSchedule(Schedule p0){}
}
