/* Generated by Together */

package Application;

import Business.Schedule;
public class MaintainSchedule {
    /**
     * Returns a schedule that is saved but not active. Returns null if no edited schedule exists. 
     */
    public void getEditedSchedule(int p0){}

    /**
     * Takes an array of schedules and adds the shifts of all into one, which is returned. 
     */
    public Schedule mergeSchedule(Schedule[] p0){}

    /**
     * Sets the schedule for a certain day (the string param is a date) with the shift[] 's specified. 
     */
    protected void setSchedule(String p0, Shift[] p1){}

    /**
     * Clears a schedule by removing all shifts 
     */
    public void clearSchedule(Schedule p0){}
}
