/* Generated by Together */

package Application;

import Business.Schedule;

/**
 * Provides functionality for all actions used by the Maintain Employee use case. 
 */
public class MaintainEmployee {
    /**
     * Sets an employee's availability with a new value. 
     */
    public void setAvailability(Schedule p0){}

    /**
     * Send a schedule into pending state for a change in availability. 
     */
    public void pendingAvailability(Schedule p0){}
}
