/* Generated by Together */

package Application;

/**
 * Provides functionality for auto-generating schedules. 
 */
public class ScheduleGenerator {
    /**
     * Generates a new schedule based off of a schedule template. The returned schedule will contain all available employees that matched the required positions of the template, as well as the given location.
     * 
     *  If the system was unable to fully meet the requirements of the template (E.g., only 4 people found available to work a shift, but 5 are needed), then additional employees that are capable of working the position, but have a different preferred will be inserted (grouped by shift and position) into the given ArrayList parameter. 
     */
    public Schedule generateSchedule() {
    }
}
