/* Generated by Together */

package Interface.location;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Used to add a location to the database using the location management screen. 
 */
public class AddLocation extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
