/* Generated by Together */

package Interface.user;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Resets the password of a user. If the sending option was selected, an email is sent to the user. If the user's email is empty, an email is sent to the Admin who is resetting the password 
 */
public class ResetPassword extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
