/* Generated by Together */

package Interface.user;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Used to update a user's profile in the database. It will be called from the update user screen in Web Agenda. 
 */
public class UpdateUser extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
