/* Generated by Together */

package ProblemDomain;

/**
 * Contains information on an employee within the system including username and passwords to log in, and basic employee information such as first and last name. 
 */
public class Employee {
    public Shift[] getShifts(){}

    public void getLoginTimes(){}

    public void getViewTimes(){}

    /**
     * The first name of the employee. 
     */
    private String fName;

    /**
     * The last name of the employee. 
     */
    private String lName;

    /**
     * The username that the employee uses to log into the system. 
     */
    private String username;

    /**
     * The password that the employee uses to log into the system. 
     */
    private String password;

    /**
     * The ID number of the employee within the system. 
     */
    private int empId;
    private PermissionLevel plvl;

    /**
     * Employees will receive and view notifications that are sent automatically, or manually sent by their supervisor. 
     * @clientCardinality 0..1
     * @supplierCardinality 0..*
     * @clientQualifier is sent to
     * @supplierQualifier receives
     */
    private Notification lnkNotification;

    /**
     * Multiple employees can work the same shift, and an employee can work multiple shifts. 
     * @clientCardinality 1
     * @supplierCardinality 0..*
     * @clientQualifier belongs to
     * @supplierQualifier has
     */
    private Shift lnkShift;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 1
     * @clientQualifier applies to
     * @supplierQualifier has
     */
    private JobType lnkEmployeeType;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 1
     * @supplierQualifier has
     * @clientQualifier applies to 
     */
    private PermissionLevel lnkPermissionLevel;
}
