/* Generated by Together */

package ProblemDomain;

public class Event {
    public void newEvent(Event event){}

    private JobType empType;
    private Workgroup workgroup;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 0..*
     * @clientQualifier may have
     * @supplierQualifier applies to 
     */
    private JobType lnkJobType;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 0..*
     * @clientQualifier may have
     * @supplierQualifier applies to 
     */
    private Workgroup lnkWorkgroup;
}
