/* Generated by Together */

package ProblemDomain;

/**
 * A notification is a type of message object that is sent to employees.  These can be sent out automatically to inform an employee of the status of requests they have made, and can also be sent manually if a supervisor wishes to send a message to his/her employees. 
 */
public class Notification {
    /**
     * This method just creates a new notificaiton object and sends it out to every employee that has a new schedule implemented. 
     */
    public void sendNotification() {
    }

    /**
     * Shows whether or not the intended recipient of this notification has opened and viewed it. 
     */
    private boolean wasViewed;

    /**
     * Contains the message text of the notification. 
     */
    private String message;

    /**
     * Contains the type of notification that this object represents, such as an accept/reject notification for an employee request, or a general notification sent by the supervisor. 
     */
    private String typeOfNotifier;
}
