/* Generated by Together */

package ProblemDomain;

/**
 * Supervisors by default have full employee credentials, and are able to access all features that are available to employees.  In addition, supervisors may access special features, allowing them to add new employees in the system and create new workgroups, shifts and schedules. 
 */
public class Supervisor extends Employee {
    /**
     * Gets a list of all employee workgroups that the supervisor is in charge of. 
     */
    public Object[] fetchWorkgroups(){}

    public void getWorkgroupList(){}

    /**
     * A collection of all employees that the supervisor is in charge of, stored as a list of the ID's of those employees. 
     */
    private int[] employees;
    private Object[] workgroupList;

    /**
     * A supervisor may be in charge of multiple workgroups, which they have created for their employees. 
     */
    private Workgroup lnkWorkgroup;

    /**
     * Supervisors may view notifications created by the system, as well as manually create notifications to send to their employees. 
     */
    private Notification lnkNotification;
}
