/* Generated by Together */

package Interface.Settings;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Will check to see if the passwords match when a change password request has been submitted. 
 */
public class ConnectResetPassword extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
