/* Generated by Together */

package Business;

/**
 * Empty interface class, extended by all business objects so that they can be passed into and retrieved from broker classes. 
 */
public interface BusinessObject {
}
