/* Generated by Together */

package Business;

/**
 * Locations are used to keep track of specific real-world places.  An employee may have a preferred location to work in, used by the schedule and report generators.
 */
public class Location {
    /**
     * The name of the location, uniquely identifying it apart from other locations. 
     */
    private String name;

    /**
     * The description of the location, if desired. 
     */
    private String description;
}
