/* Generated by Together */

package Business;

/**
 * Supervisors by default have full employee credentials, and are able to access all features that are available to employees.  In addition, supervisors may access special features, allowing them to add new employees in the system and create new workgroups, shifts and schedules. 
 */
public class Location {
    private String name;
    private String description;
}
