/* Generated by Together */

package Business;

/**
 * A notification is a type of message object that is sent to employees.  These can be sent out automatically to inform an employee of the status of requests they have made, and can also be sent manually if a supervisor wishes to send a message to his/her employees. 
 */
public class Notification {
    public void sendNotification(){}

    private int senderID;
    private int recipientID;
    private Date sentTime;

    /**
     * Shows whether or not the intended recipient of this notification has opened and viewed it. 
     */
    private boolean viewed;

    /**
     * Contains the message text of the notification. 
     */
    private String message;

    /**
     * Contains the type of notification that this object represents, such as an accept/reject notification for an employee request, or a general notification sent by the supervisor. 
     */
    private String type;
}
