/* Generated by Together */

package Business;

public class Position {
    private String name;
    private String description;

    /**
     * @clientQualifier requires
     * @supplierCardinality 1..*
     * @supplierQualifier included in
     * @clientCardinality 0..* 
     */
    private Skill lnkSkill;
}
