/* Generated by Together */

package Business;

/**
 * Represents a Position that an employee can work. It is used extensively in Scheduling for auto-generation; it places employees that can work certain positions in those positions that are required for a completely schedule to be generated.
 */
public class Position implements BusinessObject {
    /**
     * This attribute represents the name of the position. It is unique and should accurately represent the the position.
     */
    private String positionName;

    /**
     * This attribute is a description of the name of the position. It is optional, but may aid in informed decisions that new users may require when scheduling.
     */
    private String positionDescription;

    /**
     * An array or list of strings, indicating all of the skills that this position requires. 
     */
    private String[] reqSkills;

    /**
     * @clientQualifier requires
     * @supplierCardinality 1..*
     * @supplierQualifier included in
     * @clientCardinality 0..* 
     */
    private Skill lnkSkill;
}
