/* Generated by Together */

package Business;

/**
 * Stores all information on a specific schedule, matching the structure of the database.  A filled schedule will list what days and times a set of employees are working.
 * 
 * May also be used as a template when searching for schedules in the system.
 */
public class Schedule {
    /**
     * The internal DB ID of the schedule.  This is for broker use only. 
     */
    private int schedID;

    /**
     * The ID of the employee who created this schedule.
     */
    private int creatorID;

    /**
     * The start date for when this schedule will be in effect for all applicable employees.
     */
    private Date startDate;

    /**
     * The end date for when this schedule will no longer be in effect for all applicable employees.
     */
    private Date endDate;

    /**
     * The collection of shifts that will be active between the dates set by the schedule.
     */
    private Shift[] shifts;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 1
     * @supplierQualifier may create
     * @clientQualifier is created by 
     */
    private Employee lnkEmployee;
}
