/* Generated by Together */

package Business;

/**
 * A group of working shifts that apply within a given range of dates.
 */
public class Schedule {
    public WorkingShift[] getWorkingShifts(){}

    /**
     * The start date for when this schedule will be in effect for all applicable employees.
     */
    private Date startDate;

    /**
     * The end date for when this schedule will no longer be in effect for all applicable employees.
     */
    private Date endDate;

    /**
     * The collection of working shifts that will be active between the dates set by the schedule.
     */
    private WorkingShift[] workingShifts;
    private int creatorID;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 1
     * @supplierQualifier may create
     * @clientQualifier is created by 
     */
    private Employee lnkEmployee;
}
