/* Generated by Together */

package Business;

/**
 * Defines the start and end time of a shift for a set of required positions.
 */
public class ShiftTemplate implements BusinessObject {
    /**
     * The internal DB ID of the shift template. This is for broker use only. 
     */
    private int shiftTempID;

    /**
     * The internal DB ID of the schedule template that the shift belongs to. This is for broker use only. 
     */
    private int schedTempID;

    /**
     * The day of the week that the shift is on. 
     */
    private int day;

    /**
     * The time at which the shift begins.
     */
    private Time startTime;

    /**
     * The time at which the shift ends.
     */
    private Time endTime;

    /**
     * An array or list of all shift positions for this shift template.
     */
    private ShiftPos[] positions;

    /**
     * @clientQualifier contains
     * @supplierCardinality 1..*
     * @supplierQualifier required by
     * @clientCardinality 1 
     */
    private ShiftPos lnkShiftPos;
}
