/* Generated by Together */

package Business;

public class ShiftPos {
    private Position position;
    private int count;

    /**
     * @clientQualifier contains
     * @supplierCardinality 1
     * @supplierQualifier required by
     * @clientCardinality 0..* 
     */
    private Position lnkPosition;
}
