/* Generated by Together */

package Business;

/**
 * Defines the the day of the week, start time and end time of a shift for a set of employees.
 */
public class Shift implements BusinessObject {
    /**
     * The internal DB ID of the shift. This is for broker use only. 
     */
    private int shiftID;

    /**
     * The internal DB ID of the schedule the shift belongs to. This is for broker use only. 
     */
    private int schedID;

    /**
     * The day of the week that the shift is on. 
     */
    private int day;

    /**
     * The time at which the shift begins.
     */
    private Time startTime;

    /**
     * The time at which the shift ends.
     */
    private Time endTime;

    /**
     * The array or list of all employees that are working on the shift.
     */
    private Employee[] employees;

    /**
     * @supplierQualifier contains
     * @clientCardinality 1..*
     * @clientQualifier is contained by
     * @supplierCardinality 1 
     */
    private Schedule lnkSchedule;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 1..*
     * @clientQualifier contains
     * @supplierQualifier works 
     */
    private Employee lnkEmployee;
}
