/* Generated by Together */

package Business;

/**
 * A workgroup is a collection of employees, grouped together by a supervisor.  It can be used to view workgroup specific schedules, or to print reports on a specific set of employees rather than all that the supervisor is in charge of. 
 */
public class Skill {
    private String name;
    private String description;
}
