/* Generated by Together */

package Business;

/**
 * Skills are assigned to both Employees and Positions.  Together, they keep track of what skills an employee must have to work a certain position, and are checked against an employee's skill list when an attempt is made to assign a preferred position to them.
 */
public class Skill {
    /**
     * The name of the skill, uniquely identifying it apart from other skills. 
     */
    private String name;

    /**
     * The description of the skill, if desired. 
     */
    private String description;
}
