/* Generated by Together */

package Business;

/**
 * Working shifts determine which employees are working at what times for a specific schedule.
 */
public class WorkingShift {
    /**
     * Returns an array containing the start and end time of a working shift. 
     */
    public Time[] getTimes(){}

    /**
     * The starting time of this working shift. 
     */
    private Time startTime;

    /**
     * The end time of this working shift. 
     */
    private Time endTime;

    /**
     * The employees that will be working during the times set by the working shift. 
     */
    private Employee[] employees;

    /**
     * @supplierQualifier contains
     * @clientCardinality 1..*
     * @clientQualifier is contained by
     * @supplierCardinality 1 
     */
    private Schedule lnkSchedule;

    /**
     * @clientCardinality 0..*
     * @supplierCardinality 1..*
     * @clientQualifier contains
     * @supplierQualifier works 
     */
    private Employee lnkEmployee;
}
