/* Generated by Together */

package Interface.users;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Will update the user information from the requested form in the update user screen of Web Agenda. 
 */
public class UpdateUserInfo extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
