/* Generated by Together */

package Interface.users;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Class that grabs Notification information from the Broker and parses it into an appropriate format or grabs specific entries for displaying in interface. 
 */
public class UserNotifications extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
