/* Generated by Together */

package Interface.position;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Used to delete a position in the system by using the delete link in the position management screen. 
 */
public class DeletePosition extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
