/* Generated by Together */

package Interface.schedule;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * Used to create a schedule from the create schedule screen. 
 */
public class ScheduleCreate extends HttpServlet  {
    public String getServletInfo(){
        return "Servlet description";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException{
        //
        //Write your code here
        //
    }
}
