/* Generated by Together */

package Persistance;

import ProblemDomain.Workgroup;
public class EventBroker {
    public void createEvent(Workgroup wrkgp, String message, date start, date end){}

    public void createEvent(JobType type, String message, date start, date end){}
}
