/* Generated by Together */

package Persistance;

import ProblemDomain.Supervisor;
import ProblemDomain.JobType;
public class JobTypeBroker {
    public String[] getJobTypeList(Supervisor supervisor) {
    }
}
