/* Generated by Together */

package Persistance;

import ProblemDomain.Schedule;
public class ScheduleBroker {
    public Schedule getDefault(String p0, String p1){}

    public Schedule[] getSchedules(String startDate, String endDate){}
}
