/* Generated by Together */

package Persistance;

public class WorkgroupBroker {
    public void getWorkgroup(){}

    public void getWorkgroups(){}

    public String[] getWorkgroupList(Supervisor supervisor){}
}
