/* Generated by Together */

package Persistance;

/**
 * Provides functionality for accessing workgroup data from the database. 
 */
public class WorkgroupBroker {
    /**
     * Returns a specific workgroup. 
     */
    public void getWorkgroup(){}

    /**
     * Returns a collection of all workgroups that a supervisor is responsible for. 
     */
    public void getWorkgroups(){}

    /**
     * Returns a collection of the names of all workgroups, rather than the workgroups themselves.  This is primarily used for lists which are then used to choose a specific workgroup to access. 
     */
    public String[] getWorkgroupList(Supervisor supervisor){}

    /**
     * Gets a new, empty workgroup that can then have employees assigned to it. 
     */
    public Workgroup getNew(){}

    /**
     * Saves the given workgroup object to the database. 
     */
    public void save(Workgroup p0){}

    /**
     * Deletes the given workgroup object from the database. 
     */
    public void delete(Workgroup p0){}
}
