/* Generated by Together */

package Persistance;

import ProblemDomain.Skill;

/**
 * Provides functionality for accessing event data from the database. 
 */
public class EventBroker {
    /**
     * Creates an event that will apply to all employees within a specified workgroup. 
     */
    public void createEvent(Skill wrkgp, String message, date start, date end){}

    /**
     * Creates an event that will apply to all employees within a specified job type. 
     */
    public void createEvent(JobType type, String message, date start, date end){}
}
