/* Generated by Together */

package Persistance;

/**
 * Provides functionality for accessing supervisor data from the database. 
 */
public class SupervisorBroker extends EmployeeBroker {
    /**
     * Gets the supervisor object for the employee that is currently logged in, assuming they have the required permissions to be classed as a supervisor. 
     */
    public Supervisor getSupervisor(){}
}
